# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='channel',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
